language: python
cache: pip
matrix:
  include:
    - python: pypy3
      env: TOXENV=pypy3
    - python: pypy
      env: TOXENV=pypy
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27
install:
  - travis_retry pip install coveralls tox
script:
  - travis_retry tox
after_success:
  - coveralls
